name: Deploy NTH Portal to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # --- LANGKAH DEBUG TAMBAHAN ---
      - name: Detektif Rahasia (Cek Panjang Karakter)
        run: |
          echo "Memeriksa apakah robot benar-benar membawa kuncinya:"
          echo "Panjang NTH_HOST: ${#CEK_HOST}"
          echo "Panjang NTH_USERNAME: ${#CEK_USER}"
          echo "Panjang NTH_SSH_KEY: ${#CEK_KEY}"
        env:
          CEK_HOST: ${{ secrets.NTH_HOST }}
          CEK_USER: ${{ secrets.NTH_USERNAME }}
          CEK_KEY: ${{ secrets.NTH_SSH_KEY }}
          
      # --- LANGKAH ASLI ---
      - name: Eksekusi SSH ke VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NTH_HOST }}
          username: ${{ secrets.NTH_USERNAME }}
          key: ${{ secrets.NTH_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/nusantarateknologihijau.web.id
            git fetch origin main
            git reset --hard origin/main